AllCops:
    Exclude:
        - 'spec/*.rb'
Metrics/LineLength:
    Max: 120
Metrics/MethodLength:
    CountComments: false  # count full line comments?
    Max: 30
Metrics/CyclomaticComplexity: 
    Max: 10
Metrics/PerceivedComplexity:
    Max: 10
Metrics/AbcSize:
    Max: 30
