# -*- coding: utf-8; mode: ruby -*-

require 'rake/testtask'
require 'rubocop/rake_task'

RuboCop::RakeTask.new(:rubocop) do |t|
  t.options = ['--display-cop-names']
end

# rspec for tests
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec)

task default: :spec
